### PR TITLE
Organizing components

### PR DESCRIPTION
**Pull request by ManiacMoustache**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Associated Issue(s)
Issue: <issue-43>

## Steps to Test
[ Describe how to run your AUTOMATED TESTS and any manual tests that may be need to prove your fix/feature ]
Run in the sim - this is only reorganizing and has no logic changes and so doesn't depend on hardware.
## Why?
We have a bunch of components so that it's becoming hard to find a component quickly and there is no organization.

### CODE REVIEW

**Review by hell0w0rld2 — DISMISSED** [review]
👍

**Review by Leaf-life — APPROVED** [review]
good

**Review by Leaf-life — DISMISSED** [review]
Good

**Review by Leaf-life — APPROVED** [review]
Good

**Review by hell0w0rld2 — APPROVED** [review]
👍

**Pull request merged**
