### PR TITLE
Shooting logic fix

### PR DESCRIPTION
**Pull request by ManiacMoustache**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issue(s)
Issue: <#X or issue-XX > [REMOVE THIS WHEN DONE Describe the issue you're working on here so it ties to the issue and Kanban (IMPORTANT FOR TRACKING). Make sure to create an issue if one doesn't already exist! ]

## Steps to Test
1. Run autoshoot a bunch
2. If balls are not consistent, things bad
3. If balls are consistent (overshoot/undershoot isn't important) you're good

## Changelog
Prevent balls from going into shooter when not at correct speed

## What?
Added negative runs to shooterlogic so hopper motors back down slowly if shooter is not at speed
Gives run-up and prevents balls from coasting into shooter
Also fixes issue where balls stay at front of hopper instead of moving up

## Why?
So balls are more consistent and faster

### CODE REVIEW

**Review by hell0w0rld2 — APPROVED** [review]
👍

**Review by hell0w0rld2 — APPROVED** [review]
👍

**Review by Leaf-life — APPROVED** [review]
good

**Review by hell0w0rld2 — APPROVED** [review]
👍

**Pull request merged**
